### ISSUE TITLE
Environment variable error

### ISSUE THREAD

**Issue by gknisely** [tobimensch/termsql#4]
Getting this error on Ubuntu 14.04 with Python 2.7.6

Traceback (most recent call last):
  File "/usr/local/bin/termsql", line 76, in <module>
    if os.environ.get('MORE_HELP').lower() == 'true':
AttributeError: 'NoneType' object has no attribute 'lower'

Shouldn't this just be:
if os.environ.get('MORE_HELP') == 'True':
    epilog_expanded = True

Works fine after I updated the script to the above.

**Comment by tobimensch** [comment]
Thanks for reporting this.

I recently introduced this bug when trying to make this condition
case insensitive. I should've tested it my code with unset environment
variable before commiting. :-)

You changed it to the way the code was written initially and I just commited
the fix for the fix.

If you checkout the latest code, it should be fine.

**Comment by gknisely** [comment]
Sweet.  Thanks!
